import http from 'node:http';
import {createReadStream,createWriteStream} from 'node:fs';
import {mkdir,readdir,readFile,writeFile,rename,rm,stat} from 'node:fs/promises';
import {join,basename,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomUUID,timingSafeEqual} from 'node:crypto';
import {spawn} from 'node:child_process';

const HOST=process.env.HOST||'0.0.0.0', PORT=Number(process.env.PORT||3000);
const TRACK_DIR=process.env.TRACK_DIR||'/srv/phonk-concert/tracks', TMP_DIR=process.env.TMP_DIR||'/srv/phonk-concert/tmp';
const LIMIT=Number(process.env.STORAGE_LIMIT_BYTES||5*1024**3), MAX=Number(process.env.MAX_UPLOAD_BYTES||250*1024**2);
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'', APP_DIR=dirname(fileURLToPath(import.meta.url));
const INDEX_FILE=process.env.INDEX_FILE||join(APP_DIR,'index.html');
await mkdir(TRACK_DIR,{recursive:true}); await mkdir(TMP_DIR,{recursive:true});

const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
function json(res,status,obj){const b=Buffer.from(JSON.stringify(obj));res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':b.length,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(b)}
function html(res,status,s,headers={}){const b=Buffer.from(s);res.writeHead(status,{'Content-Type':'text/html; charset=utf-8','Content-Length':b.length,'Cache-Control':'no-store','X-Frame-Options':'DENY',...headers});res.end(b)}
function cookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x.length===2))}
function body(req,max=16384){return new Promise((ok,no)=>{let n=0,a=[];req.on('data',c=>{n+=c.length;if(n>max){no(Object.assign(new Error('Istek cok buyuk'),{status:413}));req.destroy()}else a.push(c)});req.on('end',()=>ok(Buffer.concat(a).toString()));req.on('error',no)})}
function passOK(v){const a=Buffer.from(String(v||'')),b=Buffer.from(ADMIN_PASSWORD);return !!ADMIN_PASSWORD&&a.length===b.length&&timingSafeEqual(a,b)}
const sessions=new Map(), SESSION_MS=12*3600e3;
function isAdmin(req){const t=cookies(req).admin31,e=t&&sessions.get(t);return !!(e&&e>Date.now())}
function login(msg=''){return '<!doctype html><meta name=viewport content="width=device-width,initial-scale=1"><title>Admin</title><style>body{font:16px system-ui;background:#080510;color:#eee;display:grid;place-items:center;height:100vh;margin:0}form{width:min(90vw,380px);padding:24px;background:#151020;border:1px solid #ff2d9b66;border-radius:14px}input,button{width:100%;box-sizing:border-box;padding:13px;margin-top:12px;background:#090811;color:#fff;border:1px solid #ffffff33;border-radius:8px}button{background:#99165b}</style><form method=post action=/admin31/login><h2>Jenny Konser Admin</h2><input type=password name=password placeholder="Sifre" required autofocus><button>GIRIS</button>'+(msg?'<p>'+esc(msg)+'</p>':'')+'</form>'}
async function panel(msg=''){const ts=await listTracks(),used=await usedBytes();const rows=ts.map(t=>'<tr><td>'+esc(t.name)+'</td><td>'+(t.size/1048576).toFixed(2)+' MB</td><td><form method=post action=/admin31/delete><input type=hidden name=id value="'+esc(t.id)+'"><button>SIL</button></form></td></tr>').join('')||'<tr><td colspan=3>Parca yok.</td></tr>';return '<!doctype html><meta name=viewport content="width=device-width,initial-scale=1"><title>Admin</title><style>body{font:15px system-ui;background:#080510;color:#eee;margin:20px}main{max-width:900px;margin:auto}table{width:100%;border-collapse:collapse;background:#151020}td,th{padding:10px;border-bottom:1px solid #ffffff1a;text-align:left}button{padding:8px 12px;background:#99165b;color:white;border:0;border-radius:7px}</style><main><h1>Jenny Konser Admin</h1><p>'+(used/1073741824).toFixed(2)+' / '+(LIMIT/1073741824).toFixed(0)+' GB · '+ts.length+' sarki</p>'+(msg?'<p>'+esc(msg)+'</p>':'')+'<form method=post action=/admin31/logout><button>CIKIS</button></form><table><tr><th>Sarki</th><th>Boyut</th><th></th></tr>'+rows+'</table></main>'}
function cleanName(s){return String(s||'parca').replace(/[\x00-\x1f\x7f]/g,' ').trim().replace(/\.[a-z0-9]{1,8}$/i,'').slice(0,120)||'parca'}
async function usedBytes(){let n=0;for(const f of await readdir(TRACK_DIR))if(f.endsWith('.webm'))try{n+=(await stat(join(TRACK_DIR,f))).size}catch{}return n}
async function listTracks(){const out=[];for(const f of await readdir(TRACK_DIR)){if(!f.endsWith('.webm'))continue;const id=f.slice(0,-5),p=join(TRACK_DIR,f);let m={},st;try{m=JSON.parse(await readFile(join(TRACK_DIR,id+'.json'),'utf8'))}catch{}try{st=await stat(p)}catch{continue}out.push({id,name:cleanName(m.name||id),file:'/tracks/'+encodeURIComponent(f),mime:'audio/webm',codec:'opus',bitrate:32000,size:st.size,duration:Number(m.duration||0),added:Number(m.added||st.mtimeMs)})}return out.sort((a,b)=>b.added-a.added)}
function run(cmd,args,capture=false){return new Promise((ok,no)=>{const p=spawn(cmd,args,{stdio:['ignore',capture?'pipe':'ignore','pipe']});let o='',e='';if(capture)p.stdout.on('data',d=>o+=d);p.stderr.on('data',d=>{if(e.length<12000)e+=d});p.on('error',no);p.on('close',c=>c===0?ok(o):no(new Error(e.trim()||cmd+' cikis '+c)))})}
async function receive(req,p){return new Promise((ok,no)=>{const w=createWriteStream(p,{flags:'wx'});let n=0,bad=false;const fail=e=>{if(bad)return;bad=true;w.destroy();no(e)};req.on('data',c=>{n+=c.length;if(n>MAX){fail(Object.assign(new Error('Dosya 250 MB sinirini asiyor'),{status:413}));req.destroy()}});req.on('error',fail);req.on('aborted',()=>fail(new Error('Yukleme yarida kesildi')));w.on('error',fail);w.on('finish',()=>!bad&&ok(n));req.pipe(w)})}
async function serve(req,res,p,type,cache='no-cache'){let st;try{st=await stat(p)}catch{return false}if(!st.isFile())return false;const h={'Content-Type':type,'Accept-Ranges':'bytes','Cache-Control':cache};const r=req.headers.range;if(r&&/^bytes=\d*-\d*$/.test(r)){const m=r.match(/^bytes=(\d*)-(\d*)$/);let a=m[1]?+m[1]:0,b=m[2]?+m[2]:st.size-1;b=Math.min(b,st.size-1);if(a<0||b<a||a>=st.size){res.writeHead(416,{...h,'Content-Range':'bytes */'+st.size});res.end();return true}res.writeHead(206,{...h,'Content-Range':'bytes '+a+'-'+b+'/'+st.size,'Content-Length':b-a+1});if(req.method==='HEAD')res.end();else createReadStream(p,{start:a,end:b}).pipe(res);return true}res.writeHead(200,{...h,'Content-Length':st.size});if(req.method==='HEAD')res.end();else createReadStream(p).pipe(res);return true}
const rate=new Map();function rateOK(ip){const now=Date.now(),a=(rate.get(ip)||[]).filter(t=>now-t<600e3);if(a.length>=8)return false;a.push(now);rate.set(ip,a);return true}
let queue=Promise.resolve();function serial(fn){const n=queue.then(fn,fn);queue=n.catch(()=>{});return n}

const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://'+(req.headers.host||'localhost'));
if(req.method==='GET'&&u.pathname==='/admin31')return html(res,200,isAdmin(req)?await panel():login());
if(req.method==='POST'&&u.pathname==='/admin31/login'){const f=new URLSearchParams(await body(req));if(!passOK(f.get('password')))return html(res,401,login('Sifre yanlis.'));const t=randomUUID()+randomUUID();sessions.set(t,Date.now()+SESSION_MS);res.writeHead(303,{Location:'/admin31','Set-Cookie':'admin31='+t+'; Path=/admin31; HttpOnly; Secure; SameSite=Strict; Max-Age=43200'});return res.end()}
if(req.method==='POST'&&u.pathname==='/admin31/logout'){const t=cookies(req).admin31;if(t)sessions.delete(t);res.writeHead(303,{Location:'/admin31','Set-Cookie':'admin31=; Path=/admin31; Max-Age=0'});return res.end()}
if(req.method==='POST'&&u.pathname==='/admin31/delete'){if(!isAdmin(req))return html(res,401,login('Tekrar giris yap.'));const id=String(new URLSearchParams(await body(req)).get('id')||'');if(!/^[a-f0-9-]{30,50}$/i.test(id))return html(res,400,await panel('Gecersiz kimlik.'));await rm(join(TRACK_DIR,id+'.webm'),{force:true});await rm(join(TRACK_DIR,id+'.json'),{force:true});return html(res,200,await panel('Sarki silindi.'))}
if(req.method==='GET'&&u.pathname==='/api/health')return json(res,200,{ok:true,codec:'opus',bitrate:32000,storageLimit:LIMIT});
if(req.method==='GET'&&u.pathname==='/api/storage'){const used=await usedBytes();return json(res,200,{used,limit:LIMIT,free:Math.max(0,LIMIT-used)})}
if(req.method==='GET'&&u.pathname==='/api/tracks')return json(res,200,await listTracks());
if(req.method==='POST'&&u.pathname==='/api/upload'){const ip=String(req.headers['x-real-ip']||req.socket.remoteAddress||'x');if(!rateOK(ip))return json(res,429,{error:'Cok fazla yukleme. Biraz sonra dene.'});if(Number(req.headers['content-length']||0)>MAX)return json(res,413,{error:'Dosya 250 MB sinirini asiyor.'});const id=randomUUID(),input=join(TMP_DIR,id+'.upload'),tmp=join(TMP_DIR,id+'.webm'),audio=join(TRACK_DIR,id+'.webm'),meta=join(TRACK_DIR,id+'.json'),name=cleanName(decodeURIComponent(u.searchParams.get('name')||'parca'));try{await receive(req,input);await run('ffmpeg',['-hide_banner','-loglevel','error','-nostdin','-y','-i',input,'-map','0:a:0','-vn','-ac','2','-c:a','libopus','-b:a','32k','-vbr','constrained','-compression_level','10','-application','audio','-f','webm',tmp]);const st=await stat(tmp);let dur=0;try{dur=Number((await run('ffprobe',['-v','error','-show_entries','format=duration','-of','default=nw=1:nk=1',tmp],true)).trim())||0}catch{}await serial(async()=>{if(await usedBytes()+st.size>LIMIT)throw Object.assign(new Error('Ortak 5 GB muzik deposu dolu.'),{status:507});await rename(tmp,audio);await writeFile(meta,JSON.stringify({id,name,added:Date.now(),duration:dur}))});return json(res,201,{id,name,file:'/tracks/'+id+'.webm',mime:'audio/webm',codec:'opus',bitrate:32000,size:st.size,duration:dur})}catch(e){return json(res,e.status||500,{error:e.message})}finally{await rm(input,{force:true}).catch(()=>{});await rm(tmp,{force:true}).catch(()=>{})}}
if((req.method==='GET'||req.method==='HEAD')&&(u.pathname==='/'||u.pathname==='/index.html')){if(await serve(req,res,INDEX_FILE,'text/html; charset=utf-8'))return;return json(res,500,{error:'index.html yok'})}
if((req.method==='GET'||req.method==='HEAD')&&u.pathname.startsWith('/tracks/')){const f=basename(decodeURIComponent(u.pathname.slice(8)));if(/^[a-f0-9-]+\.webm$/i.test(f)&&await serve(req,res,join(TRACK_DIR,f),'audio/webm','public, max-age=86400'))return;return json(res,404,{error:'Parca yok'})}
return json(res,404,{error:'Bulunamadi'});
}catch(e){json(res,500,{error:e.message||'Sunucu hatasi'})}});
server.listen(PORT,HOST,()=>console.log('Jenny concert http://'+HOST+':'+PORT+' | admin /admin31 | Opus 32 kbps | 5 GiB'));
